channels:
  - piechottam
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bioconductor-biostrings
  - bioconductor-bsgenome
  - bioconductor-genomeinfodb
  - bioconductor-genomicranges
  - bioconductor-iranges
  - bioconductor-plyranges
  - biopython
  - click
  - coreutils
  - gawk
  - jacusa2
  - pandas
  - pyyaml
  - r-cowplot
  - r-curl
  - r-data.table
  - r-dplyr
  - r-ggplot2
  - r-ggpubr
  - r-jacusa2helper
  - r-magrittr
  - r-optparse
  - r-pheatmap
  - r-stringr
  - r-tidyr
  - r-yardstick
  - samtools==1.16.1
  - snakemake<8
