channels:
  - piechottam
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bioconductor-biostrings
  - bioconductor-bsgenome
  - bioconductor-genomeinfodb
  - bioconductor-genomicranges
  - bioconductor-iranges
  - bioconductor-plyranges
  - biopython
  - infernal
  - click
  - coreutils
  - gawk
  - gzip
  - jacusa2
  - pandas
  - python
  - pysam
  - pyyaml
  - r-curl
  - r-data.table
  - r-dplyr
  - r-ggplot2
  - r-patchwork
  - r-optparse
  - r-stringr
  - r-tidyr
  - r-tinytex
  - r-yardstick
  - r-knitr
  - samtools
  - snakemake
  - pdfcrop.pl
