channels:
  - piechottam
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bioconductor-biostrings
  - bioconductor-bsgenome
  - bioconductor-genomeinfodb
  - bioconductor-genomicranges
  - bioconductor-iranges
  - bioconductor-plyranges
  - biopython
  - infernal
  - click
  - coreutils
  - gawk
  - gzip
  - jacusa2
  - pandas
  - python<3.12
  - pysam
  - pyyaml
  - r-curl
  - r-data.table
  - r-dplyr
  - r-ggplot2
  - r-ggpubr
  - r-jacusa2helper
  - r-magrittr
  - r-patchwork
  - r-optparse
  - r-pheatmap
  - r-stringr
  - r-tidyr
  - r-yardstick
  - samtools
  - snakemake<8
  - pdfcrop.pl
  - texlive-core

