$schema: https://json-schema.org/draft/2020-12/schema
$id: https://github.com/dieterich-lab/QutRNA/workflow/schemas/config.yaml
title: QutRNA
description: Config for tRNA mapping and modification discovery
type: object
properties:
  pepfile:
    type: string
    description: Sample description
  parasail:
    type: object
    properties:
      opts:
        type: string
        description: Options for parasail
        default: -a sw_trace_striped_sat -M 1 -X 1 -e 1 -o 1 -x -d
      batch_size:
        type: integer
        description: Number of reads to process in batch before writing
        default: 1000
      threads:
        type: integer
        description: Number of threads to reserve for parasail
        default: 1
      lines:
        type: integer
        description: Number of lines to split FASTQ files.
        default: 0
    default: {}
  jacusa2:
    type: object
    properties:
      jar:
        type: string
        default: jacusa2
      opts:
        type: string
        default: -m 1 -q 1 -p 1 -D -i -a D,Y -P1 FR-SECONDSTRAND -P2 FR-SECONDSTRAND
      min_cov:
        type: integer
        default: 10
      threads:
        type: integer
        default: 2
    default: {}
  cmalign:
    type: object
    properties:
      opts:
        type: string
        default: --notrunc --nonbanded -g
      threads:
        type: integer
        default: 2
    default: {}
  preprocess:
    type: object
    properties:
      filter:
        type: string
      calmd:
        type: boolean
    default:
      filter: "-F 3328"
      calmd: true
  params:
    type: object
    properties:
      precision:
        type: number
        description: Calibrate alignment score offset with precision
      min_aln_score:
        type: integer
        description: Minimum alignment score to considert for calibration
    required:
      - precision
      - min_aln_score
  plots:
    type: array
    items:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        trnas:
          type: string
          enum: ["isoacceptor", "isodecoder", "all"]
        positions:
          type: array
          items:
            type: string
        opts:
          type: string
      required:
        - id
        - trnas
  samtools:
    type: object
    properties:
      threads:
        type: integer
        default: 2
    default: {}
  include:
    type: object
    properties:
      ref_fasta:
        type: string
        enum: ["link", "copy"]
        default: link
      cm:
        type: string
        enum: ["link", "copy"]
        default: copy
      mods:
        type: object
        properties:
          file:
            type: string
            enum: ["link", "copy"]
            default: copy
          abbrevs:
            type: string
            enum: ["link", "copy"]
            default: copy
        default: {}
      fastq:
        type: string
        enum: ["link", "copy"]
        default: link
      bam:
        type: string
        enum: ["link", "copy"]
        default: link
    default: {}
required:
  - pepfile
