$schema: https://json-schema.org/draft/2020-12/schema
$id: https://github.com/dieterich-lab/QutRNA/workflow/schemas/config.yaml
title: QutRNA
description: Config for tRNA mapping and modification discovery
type: object
properties:
  pepfile:
    type: string
    description: Sample description
  parasail:
    type: object
    properties:
      opts:
        type: string
        description: Options for parasail
        default: sw_trace_striped_sat -M 1 -X 1 -e 1 -o 1 -x -d -b 100000
      lines:
        type: integer
        description: Number of lines to split FASTQ files.
        default: 0
    default: {}
  gpu:
    type: object
    properties:
      pre:
        type: string
        description: BASH code to execute before GPU-assisted alignment
      opts:
        type: string
        description:
        default: --scoring 1,-1,-1,-1 --batchsize 100000
    default: {}
  jacusa2:
    type: object
    properties:
      jar:
        type: string
        default: jacusa2
      opts:
        type: string
        default: -f X:reads:nonref_ratio:insertion_ratio:deletion_ratio -u DirMult:subsampleRuns=100 -m 1 -q 1 -D -i -P1 FR-SECONDSTRAND -P2 FR-SECONDSTRAND
      min_cov:
        type: integer
        default: 10
    default: {}
  cmalign:
    type: object
    properties:
      opts:
        type: string
        default: --notrunc --nonbanded -g
    default: {}
  call_filtered:
    type: boolean
    default: false
  filter:
    type: object
    properties:
      random_alignment:
        type: boolean
        default: false
      samtools:
        type: object
        properties:
          filter:
            type: string
          calmd:
            type: boolean
        default:
          filter: -F 3328
          calmd: true
      read_length:
        type: object
        properties:
          min:
            type: integer
            default: 0
          max:
            type: integer
            default: 0
        default: {}
      trim_cigar:
        type: boolean
        default: false
      multimapper:
        type: boolean
        default: false
      overlap:
        type: object
        properties:
          five_adapter_overlap:
            type: number
            default: 0
          trna_overlap:
            type: number
            default: 0
          three_adapter_overlap:
            type: number
            defaul: 0
          default: {}
    default: {}
  params:
    type: object
    properties:
      alignment:
        type: string
        enum: ["parasail", "gpu"]
        default: parasail
      precision:
        type: number
        description: Calibrate alignment score offset with precision
        default: 0.999
      min_aln_score:
        type: integer
        description: Minimum alignment score to considert for calibration
        default: 10
    default:
    required:
      - alignment
      - precision
      - min_aln_score
  plots:
    type: array
    items:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        trnas:
          type: string
          enum: ["isoacceptor", "isodecoder", "extended", "all"]
        positions:
          type: array
          items:
            type: string
        opts:
          type: string
      required:
        - id
        - trnas
  transform:
    type: object
    properties:
      bam:
        type: object
        properties:
          base_change:
            type: string
            enum: ["U2T", "T2U"]
          reverse:
            type: boolean
            default: false
        default: {}
    default: {}
  include:
    type: object
    properties:
      ref_fasta:
        type: string
        enum: ["link", "copy"]
        default: link
      cm:
        type: string
        enum: ["link", "copy"]
        default: copy
      mods:
        type: object
        properties:
          file:
            type: string
            enum: ["link", "copy"]
            default: copy
          abbrevs:
            type: string
            enum: ["link", "copy"]
            default: copy
        default: {}
      fastq:
        type: string
        enum: ["link", "copy"]
        default: link
      bam:
        type: string
        enum: ["link", "copy"]
        default: link
    default: {}
default: {}
required:
  - pepfile
