params:
  precision: 0.95 # Calibrate alignment score offset with precision
  min_aln_score: 10 # Minimum alignment score to consider for calibration

parasail:
  opts: # overwrite default parametes to parasail. Check "schema/config.yaml" (parasail["opts"]) for default values
  lines: # split input FASTA into number of lines. MAKE sure thisdivisble by 4!

preprocess:
  samtools:
    filter: # samtools opts, default: "-F 3328"
    callmd: true|false # set to true, to fix MD field with samtools
  read_length: # keep reads that obbey the following length criteria
    min: # default: -1, no filtering
    max: # default: -1, no filtering
  alignment_length: # keep reads that obbey the following length criteria
    min: # default: -1, no filtering
    max: # default: -1, no filtering
  trim_cigar: true|false # trim deletions, insertion, mismatches from ends of CIGAR string

jacusa2:
  min_cov: # require min cov(arge) per BAM to consider pileup by JACUSA2
  opts: # overwrite default parametes to JACUSA2. Check "schema/config.yaml" (jacusa2["opts"]) for default values

plots:
  # default plots
  - id: isodecoder # unique id for plots. Will be available under results/plots/{id}
    trnas: isodecoder # how to group tRNAs in plots: isodecoder, isoacceptor
    opts: # CLI options to scripts/plot_score.R
    position: # restrict plots to positions, e.g. [34,35,36]
  - id: isoacceptor
    trnas: isoacceptor
  # extended plots
  - id: isodecoder_extended
    trnas: isodecoder
    opts: "--sort --show_introns --show_coverage --title 'isodecoder: {amino_acid}-{anti_codon}'"
  - id: isoacceptor_extended
    trnas: isoacceptor
    opts: "--sort --show_introns --show_coverage --title 'isoacceptor: {amino_acid}'"

include: # determines how data is included in the workflow: link or copy. Check schemas/config (include) for default values.
  ref_fasta: # copy or link reference fasta.
  cm: # copy or link cm file.
  mods:
    file: # copy or link modification file.
    abbrevs: # copy or link abbrevs file.
  fastq: # copy or link FASTQ files.
  bam: # copy or link BAM files.
